import fs from 'fs';
import path from 'path';

const companies = [
  { name: "Accenture", domain: "accenture.com" },
  { name: "Fractal Analytics", domain: "fractal.ai" },
  { name: "Oracle India", domain: "oracle.com" },
  { name: "Google LLC", domain: "google.com" },
  { name: "Apple Inc.", domain: "apple.com" },
  { name: "Mitsubishi UFJ", domain: "mufg.jp" },
  { name: "Commonwealth Bank", domain: "commbank.com.au" },
  { name: "KALVI CAREER", domain: "kalvi.education" },
  { name: "Larsen & Toubro", domain: "larsentoubro.com" },
  { name: "Tata Consultancy Services", domain: "tcs.com" },
  { name: "Infosys Limited", domain: "infosys.com" },
  { name: "Cloudera", domain: "cloudera.com" },
  { name: "Guidewire", domain: "guidewire.com" },
  { name: "Amazon.com", domain: "amazon.com" },
  { name: "Llama Logisol", domain: "delhivery.com" },
  { name: "Swiggy", domain: "swiggy.com" },
  { name: "Leap Finance", domain: "leapfinance.com" },
  { name: "Cisco Systems", domain: "cisco.com" },
  { name: "Volvo Group", domain: "volvogroup.com" },
  { name: "Amadeus", domain: "amadeus.com" },
  { name: "NielsenIQ", domain: "nielseniq.com" },
  { name: "Snowflake", domain: "snowflake.com" },
  { name: "Palantir", domain: "palantir.com" },
  { name: "Oracle Financial", domain: "oracle.com" },
  { name: "IBM", domain: "ibm.com" },
  { name: "Barclays", domain: "barclays.com" },
  { name: "Schneider Electric", domain: "se.com" },
  { name: "Blink Commerce", domain: "blinkit.com" },
  { name: "Zerodha", domain: "zerodha.com" },
  { name: "Myntra", domain: "myntra.com" },
  { name: "Nurix", domain: "nurix.com" },
  { name: "Citigroup", domain: "citigroup.com" },
  { name: "ZS Associates", domain: "zs.com" },
  { name: "FLAM Gaming", domain: "flam.app" },
  { name: "SAP Labs", domain: "sap.com" },
  { name: "Xperi", domain: "xperi.com" },
  { name: "Consilio", domain: "consilio.com" },
  { name: "BT Group", domain: "bt.com" },
  { name: "Capgemini", domain: "capgemini.com" },
  { name: "BNY Mellon", domain: "bnymellon.com" },
  { name: "Fidelity", domain: "fidelity.com" },
  { name: "JPMorgan", domain: "jpmorgan.com" },
  { name: "Airbus", domain: "airbus.com" },
  { name: "Wells Fargo", domain: "wellsfargo.com" },
  { name: "Atlassian", domain: "atlassian.com" },
  { name: "Nutanix", domain: "nutanix.com" },
  { name: "DeepMind", domain: "deepmind.com" },
  { name: "Akamai", domain: "akamai.com" },
  { name: "Adobe", domain: "adobe.com" },
  { name: "Genpact", domain: "genpact.com" },
  { name: "Uber", domain: "uber.com" },
  { name: "Dell", domain: "dell.com" },
  { name: "Even Healthcare", domain: "even.in" },
  { name: "Groww", domain: "groww.in" },
  { name: "MintAir", domain: "mintair.com" },
  { name: "OpenAI", domain: "openai.com" },
  { name: "Skyhigh Security", domain: "skyhighsecurity.com" },
  { name: "SpaceX", domain: "spacex.com" },
  { name: "Walmart", domain: "walmart.com" },
  { name: "Zepto", domain: "zeptonow.com" },
  { name: "DevRev", domain: "devrev.ai" },
  { name: "Increff", domain: "increff.com" },
  { name: "MoveInSync", domain: "moveinsync.com" },
  { name: "NVIDIA", domain: "nvidia.com" },
  { name: "ServiceNow", domain: "servicenow.com" },
  { name: "Tredence", domain: "tredence.com" },
  { name: "CME Group", domain: "cmegroup.com" },
  { name: "HCL", domain: "hcltech.com" },
  { name: "Freshworks", domain: "freshworks.com" },
  { name: "HP", domain: "hp.com" },
  { name: "Philips", domain: "philips.com" },
  { name: "Warner Bros", domain: "warnerbros.com" },
  { name: "HyperVerge", domain: "hyperverge.co" },
  { name: "Motorq", domain: "motorq.com" },
  { name: "Autodesk", domain: "autodesk.com" },
  { name: "EA", domain: "ea.com" },
  { name: "Morgan Stanley", domain: "morganstanley.com" },
  { name: "Microsoft", domain: "microsoft.com" },
  { name: "Darwinbox", domain: "darwinbox.com" },
  { name: "Epifi", domain: "fi.money" },
  { name: "Juspay", domain: "juspay.in" },
  { name: "Flipkart", domain: "flipkart.com" },
  { name: "Optum", domain: "optum.com" },
  { name: "PayPal", domain: "paypal.com" },
  { name: "Bajaj Finserv", domain: "bajajfinserv.in" },
  { name: "Bain", domain: "bain.com" },
  { name: "Proactively", domain: "proactively.ai" },
  { name: "Samsung PRISM", domain: "samsung.com" },
  { name: "Acko", domain: "acko.com" },
  { name: "Robert Bosch", domain: "bosch.com" },
  { name: "Concentrix", domain: "concentrix.com" },
  { name: "Dunzo", domain: "dunzo.com" },
  { name: "Byju's", domain: "byjus.com" },
  { name: "Cleartrip", domain: "cleartrip.com" },
  { name: "Cognizant", domain: "cognizant.com" },
  { name: "DXC", domain: "dxc.technology" },
  { name: "PhysicsWallah", domain: "pw.live" },
  { name: "Udemy", domain: "udemy.com" },
  { name: "NTT DATA", domain: "nttdata.com" },
  { name: "Virtusa", domain: "virtusa.com" },
  { name: "upGrad", domain: "upgrad.com" },
  { name: "Wipro", domain: "wipro.com" },
  { name: "Paytm Money", domain: "paytmmoney.com" },
  { name: "Hexagon", domain: "hexagon.com" },
  { name: "INDmoney", domain: "indmoney.com" },
  { name: "Tech Mahindra", domain: "techmahindra.com" },
  { name: "Simplilearn", domain: "simplilearn.com" },
  { name: "BigBasket", domain: "bigbasket.com" },
  { name: "Ecom Express", domain: "ecomexpress.in" },
  { name: "Kyndryl", domain: "kyndryl.com" },
  { name: "MobiKwik", domain: "mobikwik.com" },
  { name: "Shadowfax", domain: "shadowfax.in" },
  { name: "Rupeek", domain: "rupeek.com" },
  { name: "3i Infotech", domain: "3i-infotech.com" },
  { name: "BharatPe", domain: "bharatpe.com" },
  { name: "HighRadius", domain: "highradius.com" }
];

function generateSummary() {
  const summary = [];
  companies.forEach((comp, index) => {
    const safeName = comp.name.replace(/[^a-zA-Z0-9]/g, '_');
    summary.push({
      name: comp.name,
      short_name: comp.name.split(' ')[0],
      hiring_velocity: ["High", "Moderate", "Low", "Frozen"][index % 4],
      profitability_status: ["Profitable", "Break-even", "Loss-making"][index % 3],
      remote_policy_details: ["Remote", "Hybrid", "On-site"][index % 3],
      logo_url: `https://logo.clearbit.com/${comp.domain}`,
      full_json: `/data/Companies_Full/${safeName}.json`,
      hiring_json: `/data/Hiring_Grounds/${safeName}.json`,
      innovx_json: `/data/InnoVex/${safeName}.json`
    });
  });
  
  const dest = 'public/data/summary.json';
  fs.writeFileSync(dest, JSON.stringify(summary, null, 2));
  console.log(`Updated Summary with quality logos and data paths at ${dest}`);
}

generateSummary();
